#!/usr/bin/env python3 -u
"""Generate the operator signing key that badges trust.

Every badge is built with ONE public key baked in. Commands published to a
badge - rename it, change what it shows, install firmware - are only obeyed if
they carry a signature from the matching private key. Without this, anyone who
can reach the broker can flash arbitrary firmware onto every badge you own.

  python3 tools/make_operator_key.py

Writes:
  ~/.dc34_badge_operator.pem          private key. NEVER commit or share this.
  arduino/badge/operator_pub.h        public key, compiled into the firmware.

The public half is not a secret - it is the whole point that it is published.
The private half is the thing that makes you you.

Re-running with --force mints a NEW identity: badges built with the old public
key will reject everything signed by the new one until they are reflashed over
USB. That is the intended behaviour if the private key ever leaks, and the
reason it is not the default.
"""

import argparse
import os
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

import badgeauth

HEADER = "operator_pub.h"


def emit_header(pub_bytes, path, fingerprint):
    with open(path, "w") as f:
        f.write("// operator_pub.h - generated by tools/make_operator_key.py.\n")
        f.write("// Do not edit.\n//\n")
        f.write("// The single public key this badge trusts. Commands arriving\n")
        f.write("// over MQTT are verified against it and dropped unread if the\n")
        f.write("// signature does not check out.\n//\n")
        f.write(f"// Fingerprint: {fingerprint}\n")
        f.write("//\n// Uncompressed P-256 point: 0x04 || X || Y.\n")
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write("#define OPERATOR_PUB_LEN 65\n")
        f.write(f'#define OPERATOR_FINGERPRINT "{fingerprint}"\n\n')
        f.write("static const uint8_t OPERATOR_PUB[OPERATOR_PUB_LEN] = {\n")
        for i in range(0, len(pub_bytes), 12):
            row = ", ".join(f"0x{b:02X}" for b in pub_bytes[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--key", default=badgeauth.default_key_path())
    ap.add_argument("--header", help="where to write operator_pub.h")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing key (invalidates every badge "
                         "already built with the old one)")
    a = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    header = a.header or os.path.join(here, "..", "arduino", "badge", HEADER)
    header = os.path.abspath(header)

    if os.path.exists(a.key) and not a.force:
        print(f"key already exists: {a.key}")
        key = badgeauth.load_private(a.key)
        print("(re-emitting the header from it; pass --force to mint a new one)")
    else:
        key = ec.generate_private_key(ec.SECP256R1())
        # 0600: this file is the only thing standing between the broker and
        # arbitrary firmware on every badge.
        fd = os.open(a.key, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "wb") as f:
            f.write(key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.PKCS8,
                serialization.NoEncryption()))
        print(f"wrote private key: {a.key}  (mode 0600)")

    pub = key.public_key().public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint)

    import hashlib
    fp = hashlib.sha256(pub).hexdigest()[:16]

    emit_header(pub, header, fp)
    print(f"wrote public header: {header}")
    print(f"fingerprint: {fp}")
    print("\nRebuild and flash the badges over USB for this key to take effect.")
    print("A badge running older firmware trusts the OLD key, or no key at all.")


if __name__ == "__main__":
    main()
