#!/bin/sh
# Return the stack to the image digests recorded by the last update.sh run.
#
# Generates compose.rollback.yml (git-ignored) that pins each service to the
# exact digest it was running before, and layers it over
# compose.production.yml. Configuration, volumes and credentials are untouched
# - this rolls back code, not data. If a bad *config* change is the problem,
# fix the file and re-run scripts/deploy.sh; if data is the problem, use
# scripts/restore.sh.
#
#   ./scripts/rollback.sh

set -eu

. "$(dirname -- "$0")/lib.sh"

FROM_UPDATE=no
[ "${1:-}" = "--from-update" ] && FROM_UPDATE=yes

require_docker
load_env
cd "$BROKER_DIR"

[ -s "$ROLLBACK_STATE" ] ||
	die "no rollback state recorded ($ROLLBACK_STATE). It is written by scripts/update.sh."

log "rolling back to:"
{
	echo "# Generated by scripts/rollback.sh - safe to delete."
	echo "services:"
} >"$ROLLBACK_FILE"
while IFS='=' read -r svc ref; do
	[ -n "$svc" ] || continue
	log "  $svc $ref"
	printf '  %s:\n    image: "%s"\n' "$svc" "$ref" >>"$ROLLBACK_FILE"
done <"$ROLLBACK_STATE"

# Re-pull by digest in case the images were pruned since. A digest reference is
# immutable, so this cannot bring back something different.
while IFS='=' read -r svc ref; do
	case "$ref" in
	sha256:*) continue ;; # a bare image ID cannot be pulled; it is either local or gone
	esac
	docker image inspect "$ref" >/dev/null 2>&1 || {
		log "re-pulling $ref"
		docker pull --quiet "$ref" >/dev/null || warn "could not pull $ref"
	}
done <"$ROLLBACK_STATE"

log "recreating containers at the recorded digests"
compose_rollback up -d

wait_healthy caddy 120 || warn "caddy did not report healthy after rollback"
wait_healthy mosquitto 240 || warn "mosquitto did not report healthy after rollback"

compose_rollback ps

if "$BROKER_DIR/scripts/healthcheck.sh"; then
	log "rollback validated"
else
	warn "the rolled-back stack still fails validation - the problem is probably configuration or data, not the images"
	warn "see scripts/restore.sh to go back to a backup"
	[ "$FROM_UPDATE" = yes ] || exit 1
fi

cat <<EOF

The stack is pinned by compose.rollback.yml. Keep using it for any further
compose commands while pinned:

  docker compose -f compose.production.yml -f compose.rollback.yml --env-file .env.production ps

When you are ready to move forward again, delete compose.rollback.yml and run
./scripts/deploy.sh.
EOF
