#!/bin/sh
# Provision production credentials.
#
# Generates web, operator, and health passwords into .env.production and their
# hashes into config/passwd.production. Badge accounts are enrolled separately
# and remain intact when these service credentials rotate.
#
# Deliberately separate from the bench credentials: this writes
# config/passwd.production, never config/passwd, so running it on a developer
# machine cannot invalidate a working local setup. mosquitto.conf keeps using
# config/passwd; mosquitto.production.conf uses config/passwd.production.
#
#   ./scripts/setup-production.sh            provision once, then no-op
#   ./scripts/setup-production.sh --rotate   issue new passwords
#
# After a rotation, update the web client and operator tooling. Badge passwords
# are not changed by this script.

set -eu

. "$(dirname -- "$0")/lib.sh"

ROTATE=no
[ "${1:-}" = "--rotate" ] && ROTATE=yes

require_docker
cd "$BROKER_DIR"

MOSQUITTO_IMAGE=eclipse-mosquitto:2.0.20

if [ ! -f "$ENV_FILE" ]; then
	[ -f .env.production.example ] || die ".env.production.example is missing"
	cp .env.production.example "$ENV_FILE"
	chmod 600 "$ENV_FILE"
	cat >&2 <<EOF
Created .env.production from the example.

Set DOMAIN and ACME_EMAIL in it, make sure a DNS A record for DOMAIN already
points at this instance, then run this script again.
EOF
	exit 1
fi

parse_env "$ENV_FILE"
[ -n "${DOMAIN:-}" ] || die "DOMAIN is not set in .env.production"
[ -n "${ACME_EMAIL:-}" ] || die "ACME_EMAIL is not set in .env.production"
case "$DOMAIN" in
*example.com) die "DOMAIN is still the placeholder ($DOMAIN) - set your real hostname" ;;
esac

ACL_FILE="$BROKER_DIR/config/acl.production.conf"
ACL_BASE="$BROKER_DIR/config/acl.production.base.conf"

if [ -f "$PASSWD_FILE" ] && [ -f "$ACL_FILE" ] &&
   [ -n "${WEB_PASSWORD:-}" ] && [ -n "${OPERATOR_PASSWORD:-}" ] &&
   [ -n "${HEALTH_PASSWORD:-}" ] && [ "$ROTATE" = no ]; then
	log "production credentials already exist; pass --rotate to replace them"
	exit 0
fi

random_password() {
	if command -v openssl >/dev/null 2>&1; then
		openssl rand -hex 18
	else
		# Busybox-free fallback for a minimal cloud image.
		od -An -tx1 -N18 /dev/urandom | tr -d ' \n'
		echo
	fi
}

WEB_PASSWORD=$(random_password)
OPERATOR_PASSWORD=$(random_password)
HEALTH_PASSWORD=$(random_password)

# Rewrite .env.production, keeping DOMAIN, ACME_EMAIL and any optional tuning
# the operator has set, and replacing only the credential block.
TMP_ENV=$(mktemp)
trap 'rm -f "$TMP_ENV"' EXIT
grep -v -E '^(BADGE_PASSWORD|WEB_PASSWORD|OPERATOR_PASSWORD|HEALTH_PASSWORD)=' "$ENV_FILE" |
	grep -v -E '^# Credentials generated by setup-production.sh' >"$TMP_ENV"
cat >>"$TMP_ENV" <<EOF

# Credentials generated by setup-production.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
WEB_PASSWORD=$WEB_PASSWORD
OPERATOR_PASSWORD=$OPERATOR_PASSWORD
HEALTH_PASSWORD=$HEALTH_PASSWORD
EOF
cat "$TMP_ENV" >"$ENV_FILE"
chmod 600 "$ENV_FILE"

# --user keeps the generated file owned by the invoking account. Without it the
# image's mosquitto user (uid 1883) writes into a directory it does not own,
# which fails on a stock Linux host even though it happens to work under
# Docker Desktop's uid translation.
passwd_add() {
	docker run --rm --user "$(id -u):$(id -g)" -v "$BROKER_DIR/config:/work" \
		"$MOSQUITTO_IMAGE" mosquitto_passwd "$@"
}

[ -f "$PASSWD_FILE" ] || : >"$PASSWD_FILE"
chmod 600 "$PASSWD_FILE"
passwd_add -b /work/passwd.production web "$WEB_PASSWORD"
passwd_add -b /work/passwd.production operator "$OPERATOR_PASSWORD"
passwd_add -b /work/passwd.production health "$HEALTH_PASSWORD"
chmod 600 "$PASSWD_FILE"
[ -f "$ACL_FILE" ] || cp "$ACL_BASE" "$ACL_FILE"
chmod 600 "$ACL_FILE"

log "wrote production service credentials; enrolled badge accounts were preserved"
cat <<EOF

Give these to their respective clients:

  web controller   wss://$DOMAIN/mqtt, user 'web'
                   password: $WEB_PASSWORD  (public by design; ACL-limited)
  operator tooling user 'operator'
                   password: $OPERATOR_PASSWORD

The badge firmware selects TLS by port number, so it must be given 8883.
Enroll each badge separately with:

	./scripts/enroll-badge.sh <8-hex-badge-id>
EOF

if [ "$ROTATE" = yes ]; then
	cat <<EOF

Rotated. Restart the broker to load the new password file:

  docker compose -f compose.production.yml --env-file .env.production up -d --force-recreate mosquitto
EOF
fi
